server:
 port: 9092
eureka:
 instance:
  preferIpAddress: true
  hostname: eureka-0
 client:
  service-url:
   defaultZone: http://localhost:8761/eureka/
spring:
 application:
  name: FOOD-CATALOGUE-SERVICE
 jpa:
  hibernate:
   ddl-auto: update
  show-sql: true